### PR TITLE
Rename project to "Service CA"

### PR DESCRIPTION
**Pull request by mrogers950**
No more being tongue-tied on the name :). So here is "Service CA". The binary is `service-ca`. The `service-ca` subcommands are:
- `operator`, which runs the service-ca operator
- `service-ca-signer` which runs the signing controllers (creating controller/updating controller)
- `apiservice-cabundle-injector` which runs the API service CA bundle injector controller

The namespace that these controllers run in is changing from `openshift-service-cert-signer` to `openshift-service-ca`. Corresponding references in Origin will need to be updated.

The configuration API names are left as they currently are: https://github.com/openshift/api/blob/master/servicecertsigner/v1alpha1/types.go
Should we update these as well?

### CODE REVIEW

**Comment by mrogers950** [comment]
I've updated this PR to match https://github.com/openshift/origin/pull/20870, and have done local testing to ensure that they line up properly.
@deads2k @openshift/sig-security PTAL

**Comment by deads2k** [comment]
@simo5 please confirm you want this for 3.11

**Comment by simo5** [comment]
@deads2k yes, the sooner the better, otherwise we may get upgrade issues later as context piles up

**Pull request merged**
