### PR TITLE
Remove operator from payload

### PR DESCRIPTION
**Pull request by mrogers950**
@openshift/sig-auth

### CODE REVIEW

**Comment by enj** [comment]
```
clusterversion.config.openshift.io/version condition met
test/e2e.sh
=== RUN   TestE2E
--- FAIL: TestE2E (0.09s)
	e2e_test.go:121: openshift-service-cert-signer-operator not running in openshift-core-operators namespace
FAIL
FAIL	github.com/openshift/service-serving-cert-signer/test/e2e	0.102s
make: *** [test-e2e] Error 1
```

@mrogers950 we need to disable the test (`t.Skip` is probably fine).

**Comment by ericavonb** [comment]
A quick search in github found these using the "openshift-service-cert-signer" namespace:
* https://github.com/openshift/cluster-openshift-apiserver-operator/blob/e76a99ddbcb1af0f34adec4a68dec1f091a52b30/pkg/cmd/resourcegraph/resourcegraph.go#L108
* https://github.com/openshift/cluster-kube-controller-manager-operator/blob/b8481b97b123dfa93f5d3ce80a6b4486f3d6b801/pkg/cmd/resourcegraph/resourcegraph.go#L130
* https://github.com/michaelgugino/kube-vwh/blob/master/README.md#deployment-on-openshift-cluster

Probably need to update the operator ones.

**Pull request merged**
